import { PlaceVariant } from '../types/placeVariants';

export const PLACE_CARDS: PlaceVariant[] = [
  {
    id: 'amsterdam-apt-01',
    image: 'img/apartment-01.jpg',
    price: 120,
    premium: true,
    rating: 80,
    title: 'Beautiful & luxurious apartment at great location',
    type: 'Apartment',
    bookmarked: false,
  },
  {
    id: 'amsterdam-room-01',
    image: 'img/room.jpg',
    price: 80,
    premium: false,
    rating: 80,
    title: 'Wood and stone place',
    type: 'Room',
    bookmarked: true,
  },
  {
    id: 'amsterdam-apt-02',
    image: 'img/apartment-02.jpg',
    price: 132,
    premium: false,
    rating: 80,
    title: 'Canal View Prinsengracht',
    type: 'Apartment',
    bookmarked: false,
  },
  {
    id: 'amsterdam-apt-03',
    image: 'img/apartment-03.jpg',
    price: 180,
    premium: true,
    rating: 100,
    title: 'Nice, cozy, warm big bed apartment',
    type: 'Apartment',
    bookmarked: false,
  },
  {
    id: 'amsterdam-room-02',
    image: 'img/room.jpg',
    price: 80,
    premium: false,
    rating: 80,
    title: 'Wood and stone place',
    type: 'Room',
    bookmarked: true,
  },
];
